name: create release jar

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17 and Maven
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven 
      run: mvn -pl client -am clean package -DskipTests

    - name: Upload fat Jar to GitHub Releases
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: client/target/boston-release.jar
